FROM tiangolo/uvicorn-gunicorn:python3.8-slim

RUN pip install --upgrade pip

WORKDIR /app
RUN rm /app/*

COPY requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /app/src

WORKDIR /app/src

ENV ENVIRONMENT production

CMD ["python3", "main.py"]